# services:
#   frontend:
#     build: ./frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend

#   backend:
#     build: ./backend
#     ports:
#       - "5000:5000"
#     environment:
#       DB_HOST: db
#       DB_USER: root
#       DB_PASSWORD: root
#       DB_NAME: error_db
#     depends_on:
#       - db

#   db:
#     image: mysql:8
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: error_db
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   mysql_data:

# While pulling images from the docker hub
version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: error_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: tanmaybora16/atlas-copco-backend:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: error_db
    ports:
      - "5000:5000"

  frontend:
    image: tanmaybora16/atlas-copco-frontend:latest
    ports:
      - "80:80"

volumes:
  mysql_data:
